# .eslintrc.yaml
---
  extends: eslint:recommended
  rules:
    no-console: "off"
    indent : 2
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures: 
      modules: true